import 'dart:async';
import 'package:http/http.dart' as http;
import 'package:flutter/material.dart';
import 'dart:convert';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(

        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Users'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {

  Future<List<User>> _getUsers() async{

  var data = await http.get("http://www.json-generator.com/api/json/get/cfYkBdFkwO?indent=3");
  var jsonData = json.decode(data.body);
  List<User> users = [];
  for(var u in jsonData){
    User user = User(u["index"], u["name"], u["about"], u["email"],u["picture"]);
    users.add(user);
  }
  print(users.length);
  return users;
  }


  @override
  Widget build(BuildContext context) {

    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Container(
        child: FutureBuilder(
          future: _getUsers(),
          builder: (BuildContext context, AsyncSnapshot snapshot){
            if(snapshot.data == null ){
              return Container(
                child: Center(
                  child: Text("Loading....."),
                ),
              );
            }else{
              return ListView.builder(
                itemCount: snapshot.data.length,
                itemBuilder: (BuildContext context, int index){
                  return ListTile(
                    leading: CircleAvatar(
                      backgroundImage: NetworkImage(
                        snapshot.data[index].picture,
                      ),
                    ),
                    title: Text(snapshot.data[index].name),
                    subtitle: Text(snapshot.data[index].email),
                    onTap: (){
                      Navigator.push(context,
                          new MaterialPageRoute(builder: (context) => DetailPage(snapshot.data[index])));
                    },

                  );
                },
              );
            }
          },
        ),
      )

    );
  }
}
class DetailPage extends StatelessWidget{
  final User user;
  DetailPage(this.user);
  @override
  Widget build(BuildContext context) {
    // TODO: implement build
    return Scaffold(
      appBar: AppBar(
        title: Text(user.name),
      ),
      body: Container(
        child: Text(user.about),
      ),
    );
  }

}
class User {
   List<String> category;
  String iconUrl;
  String id;
  String url;
  String value;

  Autogenerated({this.category, this.iconUrl, this.id, this.url, this.value});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    category = json['category'].cast<String>();
    iconUrl = json['icon_url'];
    id = json['id'];
    url = json['url'];
    value = json['value'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['category'] = this.category;
    data['icon_url'] = this.iconUrl;
    data['id'] = this.id;
    data['url'] = this.url;
    data['value'] = this.value;
    return data;
  }
  
}
